# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memberLoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_memberLoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginMainWidget = QtWidgets.QWidget(self.centralwidget)
        self.loginMainWidget.setEnabled(True)
        self.loginMainWidget.setGeometry(QtCore.QRect(0, 0, 1101, 611))
        self.loginMainWidget.setStyleSheet("QWidget#loginMainWidget{\n"
"background: qlineargradient(x1:0, y1:1, x2:0, y2:0, \n"
"    stop:0 #add8e6, stop:1 #ffffff);\n"
"}")
        self.loginMainWidget.setObjectName("loginMainWidget")
        self.label_3 = QtWidgets.QLabel(self.loginMainWidget)
        self.label_3.setGeometry(QtCore.QRect(480, 60, 91, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../OneDrive/Desktop/copy.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.loginMainWidget)
        self.groupBox.setGeometry(QtCore.QRect(320, 260, 411, 51))
        self.groupBox.setStyleSheet("QGroupBox#groupBox{\n"
"background-color: white;\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.MemberUsername = QtWidgets.QLineEdit(self.groupBox)
        self.MemberUsername.setGeometry(QtCore.QRect(90, 1, 321, 51))
        self.MemberUsername.setStyleSheet("font: 10pt \"Arial\";")
        self.MemberUsername.setObjectName("MemberUsername")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../OneDrive/Desktop/user.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.groupBox2 = QtWidgets.QGroupBox(self.loginMainWidget)
        self.groupBox2.setGeometry(QtCore.QRect(320, 340, 411, 51))
        self.groupBox2.setStyleSheet("QGroupBox#groupBox2{\n"
"background-color: white;\n"
"}\n"
"")
        self.groupBox2.setTitle("")
        self.groupBox2.setObjectName("groupBox2")
        self.MemberPassword = QtWidgets.QLineEdit(self.groupBox2)
        self.MemberPassword.setGeometry(QtCore.QRect(90, 1, 321, 51))
        self.MemberPassword.setStyleSheet("font: 10pt \"Arial\";")
        self.MemberPassword.setObjectName("MemberPassword")
        self.label_5 = QtWidgets.QLabel(self.groupBox2)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 31, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../OneDrive/Desktop/lock.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.MemberLoginBTN = QtWidgets.QPushButton(self.loginMainWidget)
        self.MemberLoginBTN.setGeometry(QtCore.QRect(320, 417, 411, 51))
        self.MemberLoginBTN.setStyleSheet("QPushButton#MemberLoginBTN{\n"
"     font: 87 8pt \"Segoe UI Black\";\n"
" background-color: #FAA0A0;\n"
"}")
        self.MemberLoginBTN.setObjectName("MemberLoginBTN")
        self.title = QtWidgets.QLabel(self.loginMainWidget)
        self.title.setGeometry(QtCore.QRect(320, 140, 411, 71))
        self.title.setStyleSheet("QLabel {\n"
"    font: 87 8pt \"Segoe UI Black\";\n"
"color: black\n"
"}")
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(self.loginMainWidget)
        self.label.setGeometry(QtCore.QRect(320, 210, 411, 20))
        self.label.setObjectName("label")
        self.memberBackBTN = QtWidgets.QPushButton(self.loginMainWidget)
        self.memberBackBTN.setGeometry(QtCore.QRect(20, 20, 93, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../OneDrive/Desktop/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.memberBackBTN.setIcon(icon)
        self.memberBackBTN.setObjectName("memberBackBTN")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MemberUsername.setPlaceholderText(_translate("MainWindow", "Username"))
        self.MemberPassword.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.MemberPassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.MemberLoginBTN.setText(_translate("MainWindow", "Login"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Team Member </span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Please login your credentials</p></body></html>"))
        self.memberBackBTN.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_memberLoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
