# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewLeaveRequest.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(646, 600)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 641, 601))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background: qlineargradient(x1:0, y1:1, x2:0, y2:0, \n"
"    stop:0 #add8e6, stop:1 #ffffff);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 641, 81))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 631, 20))
        self.label_4.setObjectName("label_4")
        self.requestName = QtWidgets.QLabel(self.widget)
        self.requestName.setGeometry(QtCore.QRect(20, 120, 621, 51))
        self.requestName.setObjectName("requestName")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 181, 20))
        self.label_6.setObjectName("label_6")
        self.requestType = QtWidgets.QLabel(self.widget)
        self.requestType.setGeometry(QtCore.QRect(20, 240, 221, 51))
        self.requestType.setObjectName("requestType")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(10, 350, 631, 20))
        self.label_7.setObjectName("label_7")
        self.requestReason = QtWidgets.QTextEdit(self.widget)
        self.requestReason.setEnabled(True)
        self.requestReason.setGeometry(QtCore.QRect(20, 390, 601, 101))
        self.requestReason.setStyleSheet("font: 10pt \"Arial\";")
        self.requestReason.setObjectName("requestReason")
        self.rejectRequestBTN = QtWidgets.QPushButton(self.widget)
        self.rejectRequestBTN.setGeometry(QtCore.QRect(322, 520, 291, 51))
        self.rejectRequestBTN.setStyleSheet("QPushButton#rejectRequestBTN{\n"
"background-color: #FAA0A0;\n"
"font: 10pt \"Arial\";\n"
"}\n"
"")
        self.rejectRequestBTN.setObjectName("rejectRequestBTN")
        self.approveRequestBTN = QtWidgets.QPushButton(self.widget)
        self.approveRequestBTN.setGeometry(QtCore.QRect(20, 520, 291, 51))
        self.approveRequestBTN.setStyleSheet("font: 10pt \"Arial\";")
        self.approveRequestBTN.setObjectName("approveRequestBTN")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(250, 220, 181, 20))
        self.label_8.setObjectName("label_8")
        self.requestType_2 = QtWidgets.QLabel(self.widget)
        self.requestType_2.setGeometry(QtCore.QRect(250, 240, 221, 51))
        self.requestType_2.setObjectName("requestType_2")
        self.leaveConflictNotif = QtWidgets.QLabel(self.widget)
        self.leaveConflictNotif.setGeometry(QtCore.QRect(250, 290, 391, 16))
        self.leaveConflictNotif.setStyleSheet("QLabel#leaveConflictNotif {\n"
"    color: red;\n"
"}")
        self.leaveConflictNotif.setObjectName("leaveConflictNotif")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">VIEW REQUEST</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Name:</span></p></body></html>"))
        self.requestName.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Reignear Berador Magallanes</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Type of leave:</span></p></body></html>"))
        self.requestType.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Sick Leave</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Reason:</span></p></body></html>"))
        self.requestReason.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">Ing ani man gud sir, halang akong lubot</span></p></body></html>"))
        self.rejectRequestBTN.setText(_translate("Dialog", "Reject request"))
        self.approveRequestBTN.setText(_translate("Dialog", "Approve Request"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Schedule of Leave</span></p></body></html>"))
        self.requestType_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">March 23, 2025</span></p></body></html>"))
        self.leaveConflictNotif.setText(_translate("Dialog", "*Leave conflict! 2 other leaves scheduled"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
