# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils import get_asset



class Ui_welcomeFrame(object):
    def setupUi(self, welcomeFrame):
        welcomeFrame.setObjectName("welcomeFrame")
        welcomeFrame.resize(1100, 600)
        self.welcomeMainWidget = QtWidgets.QWidget(welcomeFrame)
        self.welcomeMainWidget.setGeometry(QtCore.QRect(0, 0, 1200, 600))
        self.welcomeMainWidget.setStyleSheet("QWidget#welcomeMainWidget{\n"
"background: qlineargradient(x1:0, y1:1, x2:0, y2:0, \n"
"    stop:0 #add8e6, stop:1 #ffffff);\n"
"}")
        self.welcomeMainWidget.setObjectName("welcomeMainWidget")
        self.leftWidget = QtWidgets.QWidget(self.welcomeMainWidget)
        self.leftWidget.setGeometry(QtCore.QRect(0, 0, 521, 600))
        self.leftWidget.setObjectName("leftWidget")
        self.title = QtWidgets.QLabel(self.leftWidget)
        self.title.setGeometry(QtCore.QRect(20, 130, 501, 111))
        self.title.setStyleSheet("QLabel {\n"
"    font: 87 8pt \"Segoe UI Black\";\n"
"color: black\n"
"}")
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(self.leftWidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 511, 146))
        self.label_2.setMinimumSize(QtCore.QSize(0, 146))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.leftWidget)
        self.label.setGeometry(QtCore.QRect(10, 441, 509, 161))
        self.label.setStyleSheet("font: 8pt \"Segoe Print\";")
        self.label.setObjectName("label")
        self.TeamLeaderBTN = QtWidgets.QPushButton(self.leftWidget)
        self.TeamLeaderBTN.setGeometry(QtCore.QRect(190, 300, 161, 51))
        self.TeamLeaderBTN.setStyleSheet("QPushButton#TeamLeaderBTN{\n"
"font: 10pt \"Arial\";\n"
"}")
        self.TeamLeaderBTN.setObjectName("TeamLeaderBTN")
        self.TeamMemberBTN = QtWidgets.QPushButton(self.leftWidget)
        self.TeamMemberBTN.setGeometry(QtCore.QRect(190, 380, 161, 51))
        self.TeamMemberBTN.setStyleSheet("QPushButton#TeamMemberBTN{\n"
"font: 10pt \"Arial\";\n"
"}")
        self.TeamMemberBTN.setObjectName("TeamMemberBTN")
        self.label_3 = QtWidgets.QLabel(self.leftWidget)
        self.label_3.setGeometry(QtCore.QRect(230, 60, 91, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(get_asset("copy.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.rightWidget = QtWidgets.QWidget(self.welcomeMainWidget)
        self.rightWidget.setGeometry(QtCore.QRect(510, 20, 571, 561))
        self.rightWidget.setStyleSheet("QWidget {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.rightWidget.setObjectName("rightWidget")
        self.label_4 = QtWidgets.QLabel(self.rightWidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 571, 561))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(get_asset("wow.jpg")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(welcomeFrame)
        QtCore.QMetaObject.connectSlotsByName(welcomeFrame)

    def retranslateUi(self, welcomeFrame):
        _translate = QtCore.QCoreApplication.translate
        welcomeFrame.setWindowTitle(_translate("welcomeFrame", "Company XYZ"))
        self.title.setText(_translate("welcomeFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Welcome to <br/>COMPANY XYZ</span></p></body></html>"))
        self.label_2.setText(_translate("welcomeFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Kindly choose </span><span style=\" font-size:9pt; text-decoration: underline;\">Team Leader </span><span style=\" font-size:9pt;\">or </span><span style=\" font-size:9pt; text-decoration: underline;\">Team Member</span></p></body></html>"))
        self.label.setText(_translate("welcomeFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">&quot;Greate vision<br/>without great people is irrelevant&quot;</span></p></body></html>"))
        self.TeamLeaderBTN.setText(_translate("welcomeFrame", "Team Leader"))
        self.TeamMemberBTN.setText(_translate("welcomeFrame", "Team Member"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    welcomeFrame = QtWidgets.QFrame()
    ui = Ui_welcomeFrame()
    ui.setupUi(welcomeFrame)
    welcomeFrame.show()
    sys.exit(app.exec_())
